### ISSUE TITLE
Hide/Show Subcourse Activity based on Course Visibility

### ISSUE THREAD

**Issue by bfriesenvcc** [catalyst/moodle-mod_subcourse#42]
It would be great if the subcourse activity would automatically be hidden or shown based on the visibility of the course it's attached to. (Not sure how to label this a "Nice to Have.")

**Comment by christianwolters** [comment]
Hey @mudrd8mz,

I like this idea, have you any idea how to implement this?

Would it be a good idea to manage this via event observation, e.g. course_updated?
Or would it be a better fit to put this into a scheduled task?

Cheers
Christian

**Comment by mudrd8mz** [comment]
Similarly to how we fetch grades - I think we should have both. Event description to perform changes instantly, and (not too frequent) scheduled task to catch up eventual left-overs.

It should be per-instance behaviour, configurable at the Subcourse settings form.

**Comment by jjliaw** [comment]
Hi David:

To help troubleshoot, I am using subcourse to pull grades from hidden courses into a "main" portal course, where the subcourses serve as each unit for students, and they have the capability to view hidden courses (kind of like Stealth activities, but in this case a "stealth" subcourse!).  I had to downgrade to an older version of Subcourse in order for the hidden course grades to show up for students!

This is the beauty of Subcourse--you can build very large, complex courses, but keep them manageable since you can break apart your course into "subcourses", but to keep the student Dashboard from getting too messy, the subcourses are hidden and only the "Main" portal course shows up which then links out to each subcourse as well as aggregating the final grade.

So as a feature request, if you could create a tick box in the settings that would allow teachers to also be able to show hidden grades from hidden courses, then it would enable teachers to leverage the subcourse plugin as a way to link together many courses into a "main" or "master" course as the portal / launchpad into learning!

The default setting could be to keep hidden courses hidden from subcourse, but having the option to pull hidden grades would make Subcourse very powerful enabling teachers building large / complex courses the ability to keep things nimble / organized by using hidden "stealth" subcourses linked off the "main" portal course!

Thanks David for sharing your great work with the Moodle community!

Cheers,

--Joe

**Comment by EsdrasCaleb** [comment]
HI i made this feature on my fork (just in this fork):
https://github.com/EsdrasCaleb/moodle-mod_subcourse/tree/MOODLE_401_STABLE

and propose a push
https://github.com/catalyst/moodle-mod_subcourse/pull/82

**Comment by danmarsden** [comment]
thanks to @EsdrasCaleb this change is now in 4.1 and higher branches.
